global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 15s

    static_configs:
      - targets: ['localhost:9090']

  - job_name:  'data'
    scrape_interval: 15s

    static_configs:
      - targets: ['localhost:8080']

  - job_name:  'actuator'
    scrape_interval: 15s

    static_configs:
      - targets: ['localhost:8081']
